export const stripeResponse = {
  id: "cs_test_a1V6WMk1RmA0JKhI2vlMIrJrINvFWq62hgUnuyYbyxuBr2twbsMA4TXXDD",
  object: "checkout.session",
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 500000,
  amount_total: 500000,
  automatic_tax: {
    enabled: false,
    status: null,
  },
  billing_address_collection: null,
  cancel_url: "https://your stripe cancel page",
  client_reference_id: null,
  consent: null,
  consent_collection: null,
  currency: "inr",
  customer: "cus_LQ5C1gQ044ORtX",
  customer_creation: "always",
  customer_details: {
    address: {
      city: null,
      country: "IN",
      line1: null,
      line2: null,
      postal_code: null,
      state: null,
    },
    email: "test@gmail.com",
    name: "test",
    phone: null,
    tax_exempt: "none",
    tax_ids: [],
  },
  customer_email: null,
  expires_at: 1648785031,
  livemode: false,
  locale: null,
  metadata: {
    productId: "23",
    productName: "Web Development",
  },
  mode: "payment",
  payment_intent: "pi_1KjF1oJC3uIZHgp7ltqp53hr",
  payment_link: null,
  payment_method_options: {},
  payment_method_types: ["card"],
  payment_status: "paid",
  phone_number_collection: {
    enabled: false,
  },
  recovered_from: null,
  setup_intent: null,
  shipping: null,
  shipping_address_collection: null,
  shipping_options: [],
  shipping_rate: null,
  status: "complete",
  submit_type: null,
  subscription: null,
  success_url: "http://your success?sessionId={CHECKOUT_SESSION_ID}",
  total_details: {
    amount_discount: 0,
    amount_shipping: 0,
    amount_tax: 0,
  },
  url: null,
};
export const ProductRespone = {
  id: 22,
  title: "React + node",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do ",
  price: 45.99,
  createdAt: "2022-03-30T04:08:05.278Z",
  updatedAt: "2022-03-30T04:08:05.278Z",
  currency: "usd",
};
export const currencies = [
  {
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "&#36;",
  },
  {
    currency: "Australian Dollar",
    abbreviation: "AUD",
    symbol: "&#36;",
  },
  {
    currency: "Brazilian Real",
    abbreviation: "BRL",
    symbol: "&#82;&#36;",
  },
  {
    currency: "Canadian Dollar",
    abbreviation: "CAD",
    symbol: "&#36;",
  },
  {
    currency: "Chinese Renminbi",
    abbreviation: "CNY",
    symbol: "&#165;",
  },
  {
    currency: "Czech Koruna",
    abbreviation: "CZK",
    symbol: "&#75;&#269;",
  },
  {
    currency: "Danish Krone",
    abbreviation: "DKK",
    symbol: "&#107;&#114;",
  },
  {
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "&#8364;",
  },
  {
    currency: "Hong Kong Dollar",
    abbreviation: "HKD",
    symbol: "&#36;",
  },
  {
    currency: "Hungarian Forint",
    abbreviation: "HUF",
    symbol: "&#70;&#116;",
  },
  {
    currency: "Israeli New Sheqel",
    abbreviation: "ILS",
    symbol: "&#8362;",
  },
  {
    currency: "Japanese Yen",
    abbreviation: "JPY",
    symbol: "&#165;",
  },
  {
    currency: "Malaysian Ringgit",
    abbreviation: "MYR",
    symbol: "&#82;&#77;",
  },
  {
    currency: "Mexican Peso",
    abbreviation: "MXN",
    symbol: "&#36;",
  },
  {
    currency: "New taiwan dollar",
    abbreviation: "TWD",
    symbol: "&#78;&#84;&#36;",
  },
  {
    currency: "New Zealand Dollar",
    abbreviation: "NZD",
    symbol: "&#36;",
  },
  {
    currency: "Norwegian Krone",
    abbreviation: "NOK",
    symbol: "&#107;&#114;",
  },
  {
    currency: "Philippine Peso",
    abbreviation: "PHP",
    symbol: "&#8369;",
  },
  {
    currency: "Polish Zloty",
    abbreviation: "PLN",
    symbol: "&#122;&#322;",
  },
  {
    currency: "Pound Sterling",
    abbreviation: "GBP",
    symbol: "&#163;",
  },
  {
    currency: "Russian Ruble",
    abbreviation: "RUB",
    symbol: "&#8381;",
  },
  {
    currency: "Singapore Dollar",
    abbreviation: "SGD",
    symbol: "&#36;",
  },
  {
    currency: "swedish krona",
    abbreviation: "SEK",
    symbol: "&#107;&#114;",
  },
  {
    currency: "Swiss Franc",
    abbreviation: "CHF",
    symbol: "&#67;&#72;&#70;",
  },
  {
    currency: "Thai Baht",
    abbreviation: "THB",
    symbol: "&#3647;",
  },
];
